# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import broker_pb2 as broker__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BrokerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/cortex.BrokerService/SubmitTask',
                request_serializer=broker__pb2.TaskSubmission.SerializeToString,
                response_deserializer=broker__pb2.TaskAssignment.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/cortex.BrokerService/ClaimTask',
                request_serializer=broker__pb2.ClaimRequest.SerializeToString,
                response_deserializer=broker__pb2.TaskAssignment.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/cortex.BrokerService/CompleteTask',
                request_serializer=broker__pb2.TaskResult.SerializeToString,
                response_deserializer=broker__pb2.Acknowledgement.FromString,
                _registered_method=True)
        self.FailTask = channel.unary_unary(
                '/cortex.BrokerService/FailTask',
                request_serializer=broker__pb2.TaskFailure.SerializeToString,
                response_deserializer=broker__pb2.Acknowledgement.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cortex.BrokerService/Heartbeat',
                request_serializer=broker__pb2.HeartbeatPing.SerializeToString,
                response_deserializer=broker__pb2.HeartbeatPong.FromString,
                _registered_method=True)
        self.ListDlqTasks = channel.unary_unary(
                '/cortex.BrokerService/ListDlqTasks',
                request_serializer=broker__pb2.DlqListRequest.SerializeToString,
                response_deserializer=broker__pb2.DlqListResponse.FromString,
                _registered_method=True)
        self.ReplayTask = channel.unary_unary(
                '/cortex.BrokerService/ReplayTask',
                request_serializer=broker__pb2.ReplayRequest.SerializeToString,
                response_deserializer=broker__pb2.TaskAssignment.FromString,
                _registered_method=True)
        self.DiscardDlqTask = channel.unary_unary(
                '/cortex.BrokerService/DiscardDlqTask',
                request_serializer=broker__pb2.DiscardRequest.SerializeToString,
                response_deserializer=broker__pb2.Acknowledgement.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/cortex.BrokerService/GetSystemStatus',
                request_serializer=broker__pb2.StatusRequest.SerializeToString,
                response_deserializer=broker__pb2.SystemStatus.FromString,
                _registered_method=True)
        self.GetTaskHistory = channel.unary_unary(
                '/cortex.BrokerService/GetTaskHistory',
                request_serializer=broker__pb2.TaskHistoryRequest.SerializeToString,
                response_deserializer=broker__pb2.TaskHistoryResponse.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDlqTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscardDlqTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=broker__pb2.TaskSubmission.FromString,
                    response_serializer=broker__pb2.TaskAssignment.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=broker__pb2.ClaimRequest.FromString,
                    response_serializer=broker__pb2.TaskAssignment.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=broker__pb2.TaskResult.FromString,
                    response_serializer=broker__pb2.Acknowledgement.SerializeToString,
            ),
            'FailTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FailTask,
                    request_deserializer=broker__pb2.TaskFailure.FromString,
                    response_serializer=broker__pb2.Acknowledgement.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=broker__pb2.HeartbeatPing.FromString,
                    response_serializer=broker__pb2.HeartbeatPong.SerializeToString,
            ),
            'ListDlqTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDlqTasks,
                    request_deserializer=broker__pb2.DlqListRequest.FromString,
                    response_serializer=broker__pb2.DlqListResponse.SerializeToString,
            ),
            'ReplayTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayTask,
                    request_deserializer=broker__pb2.ReplayRequest.FromString,
                    response_serializer=broker__pb2.TaskAssignment.SerializeToString,
            ),
            'DiscardDlqTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscardDlqTask,
                    request_deserializer=broker__pb2.DiscardRequest.FromString,
                    response_serializer=broker__pb2.Acknowledgement.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=broker__pb2.StatusRequest.FromString,
                    response_serializer=broker__pb2.SystemStatus.SerializeToString,
            ),
            'GetTaskHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskHistory,
                    request_deserializer=broker__pb2.TaskHistoryRequest.FromString,
                    response_serializer=broker__pb2.TaskHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/SubmitTask',
            broker__pb2.TaskSubmission.SerializeToString,
            broker__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/ClaimTask',
            broker__pb2.ClaimRequest.SerializeToString,
            broker__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/CompleteTask',
            broker__pb2.TaskResult.SerializeToString,
            broker__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/FailTask',
            broker__pb2.TaskFailure.SerializeToString,
            broker__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/Heartbeat',
            broker__pb2.HeartbeatPing.SerializeToString,
            broker__pb2.HeartbeatPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDlqTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/ListDlqTasks',
            broker__pb2.DlqListRequest.SerializeToString,
            broker__pb2.DlqListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/ReplayTask',
            broker__pb2.ReplayRequest.SerializeToString,
            broker__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscardDlqTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/DiscardDlqTask',
            broker__pb2.DiscardRequest.SerializeToString,
            broker__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/GetSystemStatus',
            broker__pb2.StatusRequest.SerializeToString,
            broker__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.BrokerService/GetTaskHistory',
            broker__pb2.TaskHistoryRequest.SerializeToString,
            broker__pb2.TaskHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
